# service , headless, statefulset, pvc
apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  selector:
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
    
---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mongodb
    tier: database
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: mongodb
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  serviceName: mongodb-headless
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: database
    spec:
      containers:
      - name: mongodb
        image: saikumar19/mongodb:v2
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
#  PVC
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      storageClassName: "ebs-roboshop"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi